services:
  rsapa_database:
    container_name: rsapa_database
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./compose/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U ${DB_USER:-test}"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default

  rsapa_backend:
    container_name: rsapa_backend
    build:
      context: .
      dockerfile: compose/backend/Dockerfile
    depends_on:
      - rsapa_database
    env_file:
      - .env
    environment:
      STRIPE_WEBHOOK_SECRET_KEY: /run/stripe/webhook_secret
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - stripe_runtime:/run/stripe
      - ./app/:/app/app/
      - ./alembic/:/app/alembic
    networks:
      - default

  stripe-listen:
    container_name: stripe_listen
    build:
      context: .
      dockerfile: compose/stripe/Dockerfile
    env_file:
      - .env
    volumes:
      - stripe_runtime:/run/stripe
    restart: unless-stopped
    networks:
      - default


volumes:
  postgres_data:
  stripe_runtime:


networks:
  default:
    driver: bridge
