"""initial

Revision ID: 000
Revises:
Create Date: 2025-06-22 22:01:00.707585

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.domains.membership.models import SubscriptionTypeEnum

# revision identifiers, used by Alembic.
revision: str = "000"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    subscription_type_table = op.create_table(
        "subscription_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.Enum(SubscriptionTypeEnum, name="subscription_type_enum"), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_types")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("stuff", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("pending", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "user_subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subscription_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_type_id"],
            ["subscription_types.id"],
            name=op.f("fk_user_subscriptions_subscription_type_id_subscription_types"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_subscriptions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_subscriptions")),
    )

    op.bulk_insert(
        subscription_type_table,
        [
            {
                "name": "Active Member",
                "type": "ACTIVE",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Any legally qualified Russian-speaking specialist (MD, DO, MBBS, PhD, or equivalent degree). practicing pathology in the united states",
            },
            {
                "name": "Trainee Member",
                "type": "TRAINEE",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Russian-speaking residents or fellows in pathology or related disciplines in the United States.",
            },
            {
                "name": "Affiliate Member",
                "type": "AFFILIATE",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Russian-speaking pathologists, scientists, researchers, or allied professionals interested in the field of pathology whose involvement is relevant and contributes meaningfully to the Society (non-voting).",
            },
            {
                "name": "Honorary Member",
                "type": "HONORARY",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Individuals recognized fo exceptional service to the field of pathology or the Society (non-voting).",
            },
            {
                "name": "Pathway Member",
                "type": "PATHWAY",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Russian-speaking individuals pursuing or transition into a medical career in the United States. This includes medical students and internationally trained medical graduates seeking mentorship and professional development as they prepare for pathology practice in the United States (non-voting).",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_subscriptions")
    op.drop_table("users")
    op.drop_table("subscription_types")

    # enum deletion
    if op.get_bind().dialect.name == "postgresql":
        enum_type = postgresql.ENUM(name="subscription_type_enum")
        enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
