"""avatar path

Revision ID: 001
Revises: 000
Create Date: 2025-06-28 22:42:27.778725

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = "000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_path", sa.String(), nullable=True))
    op.create_unique_constraint(op.f("uq_users_avatar_path"), "users", ["avatar_path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_avatar_path"), "users", type_="unique")
    op.drop_column("users", "avatar_path")
    # ### end Alembic commands ###
