"""linked payments and membership types

Revision ID: 002
Revises: 001
Create Date: 2025-08-15 23:16:07.874955

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("membership_payments", sa.Column("membership_type_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_membership_payments_membership_type_id_membership_types"),
        "membership_payments",
        "membership_types",
        ["membership_type_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_membership_payments_membership_type_id_membership_types"), "membership_payments", type_="foreignkey"
    )
    op.drop_column("membership_payments", "membership_type_id")
    # ### end Alembic commands ###
