"""removed server default stripe_price_id

Revision ID: 003
Revises: 002
Create Date: 2025-08-22 20:05:43.422741

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "membership_types",
        "stripe_price_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'price_id_placeholder'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "membership_types",
        "stripe_price_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'price_id_placeholder'::character varying"),
    )
    # ### end Alembic commands ###
