"""phone number

Revision ID: 003
Revises: 002
Create Date: 2025-06-30 02:27:17.083625

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(length=20), nullable=True))
    op.create_unique_constraint(op.f("uq_users_phone_number"), "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_phone_number"), "users", type_="unique")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
