"""types and memberships

Revision ID: 003
Revises: 002
Create Date: 2025-08-15 23:46:35.363513

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_memberships", sa.Column("membership_type_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_users_memberships_membership_type_id_membership_types"),
        "users_memberships",
        "membership_types",
        ["membership_type_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_memberships_membership_type_id_membership_types"), "users_memberships", type_="foreignkey"
    )
    op.drop_column("users_memberships", "membership_type_id")
    # ### end Alembic commands ###
