"""linked payments and memberships

Revision ID: 004
Revises: 003
Create Date: 2025-08-16 16:02:37.670220

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_memberships", sa.Column("payment_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f("uq_users_memberships_payment_id"), "users_memberships", ["payment_id"])
    op.create_foreign_key(
        op.f("fk_users_memberships_payment_id_membership_payments"),
        "users_memberships",
        "membership_payments",
        ["payment_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_memberships_payment_id_membership_payments"), "users_memberships", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_users_memberships_payment_id"), "users_memberships", type_="unique")
    op.drop_column("users_memberships", "payment_id")
    # ### end Alembic commands ###
