"""memberships unique user_id

Revision ID: 004
Revises: 003
Create Date: 2025-08-22 23:23:29.746958

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_users_memberships_user_id"), "users_memberships", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_memberships_user_id"), "users_memberships", type_="unique")
    # ### end Alembic commands ###
