"""approval status

Revision ID: 005
Revises: 004
Create Date: 2025-08-25 22:20:20.315448

"""

from typing import Sequence, Union

import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


approval_status_enum = postgresql.ENUM("APPROVED", "REJECTED", "PENDING", name="approval_status_enum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    approval_status_enum.create(op.get_bind())
    op.add_column(
        "users_memberships",
        sa.Column("approval_status", approval_status_enum, server_default=sa.text("'PENDING'"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    approval_status_enum.drop(op.get_bind())
    op.drop_column("users_memberships", "approval_status")
    # ### end Alembic commands ###
