"""added fields into payment

Revision ID: 005
Revises: 004
Create Date: 2025-08-17 01:27:41.411450

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("membership_payments", sa.Column("customer_email", sa.String(), nullable=False))
    op.add_column("membership_payments", sa.Column("customer_name", sa.String(), nullable=False))
    op.add_column("membership_payments", sa.Column("amount_total", sa.Integer(), nullable=False))
    op.add_column("membership_payments", sa.Column("presentment_amount", sa.Integer(), nullable=True))
    op.add_column("membership_payments", sa.Column("presentment_currency", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("membership_payments", "presentment_currency")
    op.drop_column("membership_payments", "presentment_amount")
    op.drop_column("membership_payments", "amount_total")
    op.drop_column("membership_payments", "customer_name")
    op.drop_column("membership_payments", "customer_email")
    # ### end Alembic commands ###
