"""stripe price id

Revision ID: 006
Revises: 005
Create Date: 2025-08-20 21:08:05.672187

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "membership_types",
        sa.Column("stripe_price_id", sa.String(), server_default="price_id_placeholder", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("membership_types", "stripe_price_id")
    # ### end Alembic commands ###
