"""session lock fields

Revision ID: 006
Revises: 005
Create Date: 2025-08-29 21:52:27.600097

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_memberships", sa.Column("checkout_session_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users_memberships", sa.Column("checkout_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_memberships", "checkout_url")
    op.drop_column("users_memberships", "checkout_session_expires_at")
    # ### end Alembic commands ###
