"""end date nullable

Revision ID: 007
Revises: 006
Create Date: 2025-08-31 14:24:08.310715

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007"
down_revision: Union[str, None] = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users_memberships", "end_date", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users_memberships", "end_date", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###
