"""latest_invoice_id

Revision ID: 010
Revises: 009
Create Date: 2025-09-07 18:41:05.872821

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "010"
down_revision: Union[str, None] = "009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_memberships", sa.Column("latest_invoice_id", sa.String(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_users_memberships_latest_invoice_id"), "users_memberships", ["latest_invoice_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_memberships_latest_invoice_id"), "users_memberships", type_="unique")
    op.drop_column("users_memberships", "latest_invoice_id")
    # ### end Alembic commands ###
