"""payment_model

Revision ID: 011
Revises: 010
Create Date: 2025-09-07 19:10:19.608663

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "011"
down_revision: Union[str, None] = "010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ONE_TIME", "SUBSCRIPTION_INITIAL", "SUBSCRIPTION_RENEWAL", "REFUND", name="payment_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCEEDED", "PROCESSING", "FAILED", "CANCELED", "REQUIRES_PAYMENT_METHOD", name="payment_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("amount_total", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(), nullable=False),
        sa.Column("payment_intent_id", sa.String(length=128), nullable=True),
        sa.Column("charge_id", sa.String(length=128), nullable=True),
        sa.Column("invoice_id", sa.String(length=128), nullable=True),
        sa.Column("subscription_id", sa.String(length=128), nullable=True),
        sa.Column("checkout_session_id", sa.String(length=128), nullable=True),
        sa.Column("customer_id", sa.String(length=128), nullable=True),
        sa.Column("price_id", sa.String(length=128), nullable=True),
        sa.Column("product_id", sa.String(length=128), nullable=True),
        sa.Column("billing_reason", sa.String(length=64), nullable=True),
        sa.Column("receipt_url", sa.String(length=512), nullable=True),
        sa.Column("livemode", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("failure_message", sa.String(length=1024), nullable=True),
        sa.Column("payment_method_type", sa.String(length=64), nullable=True),
        sa.Column("pm_last4", sa.String(length=8), nullable=True),
        sa.Column("stripe_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_charge_id"), "payments", ["charge_id"], unique=False)
    op.create_index(op.f("ix_payments_checkout_session_id"), "payments", ["checkout_session_id"], unique=False)
    op.create_index(op.f("ix_payments_customer_id"), "payments", ["customer_id"], unique=False)
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    op.create_index(op.f("ix_payments_payment_intent_id"), "payments", ["payment_intent_id"], unique=False)
    op.create_index(op.f("ix_payments_subscription_id"), "payments", ["subscription_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_subscription_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_payment_intent_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_customer_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_checkout_session_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_charge_id"), table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
