"""update payment model

Revision ID: 012
Revises: 011
Create Date: 2025-09-07 20:48:34.118586

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "012"
down_revision: Union[str, None] = "011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payments", "stripe_customer_id", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_payments_customer_id"), table_name="payments")
    op.create_index(op.f("ix_payments_stripe_customer_id"), "payments", ["stripe_customer_id"], unique=False)
    op.drop_column("payments", "customer_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("customer_id", sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_payments_stripe_customer_id"), table_name="payments")
    op.create_index(op.f("ix_payments_customer_id"), "payments", ["customer_id"], unique=False)
    op.alter_column("payments", "stripe_customer_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
