"""payment user_id

Revision ID: 013
Revises: 012
Create Date: 2025-09-07 22:23:48.770767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "013"
down_revision: Union[str, None] = "012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("user_id", sa.Integer(), nullable=True))
    op.alter_column("payments", "invoice_id", existing_type=sa.VARCHAR(length=128), nullable=False)
    op.alter_column("payments", "subscription_id", existing_type=sa.VARCHAR(length=128), nullable=False)
    op.alter_column("payments", "stripe_customer_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("payments", "price_id", existing_type=sa.VARCHAR(length=128), nullable=False)
    op.alter_column("payments", "product_id", existing_type=sa.VARCHAR(length=128), nullable=False)
    op.alter_column("payments", "billing_reason", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("payments", "stripe_created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=True)
    op.create_foreign_key(op.f("fk_payments_user_id_users"), "payments", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_payments_user_id_users"), "payments", type_="foreignkey")
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    op.alter_column("payments", "stripe_created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("payments", "billing_reason", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column("payments", "product_id", existing_type=sa.VARCHAR(length=128), nullable=True)
    op.alter_column("payments", "price_id", existing_type=sa.VARCHAR(length=128), nullable=True)
    op.alter_column("payments", "stripe_customer_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("payments", "subscription_id", existing_type=sa.VARCHAR(length=128), nullable=True)
    op.alter_column("payments", "invoice_id", existing_type=sa.VARCHAR(length=128), nullable=True)
    op.drop_column("payments", "user_id")
    # ### end Alembic commands ###
