"""deleted filed for all models

Revision ID: 014
Revises: 013
Create Date: 2025-09-09 21:44:45.575305

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: Union[str, None] = "013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact_messages", sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "membership_types", sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column("news", sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("payments", sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("users", sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "_deleted")
    op.drop_column("payments", "_deleted")
    op.drop_column("news", "_deleted")
    op.drop_column("membership_types", "_deleted")
    op.drop_column("contact_messages", "_deleted")
    # ### end Alembic commands ###
