name: Setup envs

on:
  workflow_call:

jobs:
  setup_envs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup envs
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env

          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env

          echo "STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}" >> .env
          echo "STRIPE_EVENTS=checkout.session.completed,payment_intent.succeeded,invoice.payment_succeeded,invoice.payment_failed,payment_intent.payment_failed,customer.subscription.updated,customer.subscription.deleted,invoice.paid" >> .env
          echo "STRIPE_WEBHOOK_SECRET_KEY=${{ secrets.STRIPE_WEBHOOK_SECRET_KEY }}" >> .env

          echo "BACKEND_DOMAIN=rsapa_backend"
          echo "BACKEND_PORT=8000"

          echo "DB_PORT=5432" >> .env
          echo "DB_PASSWORD=test" >> .env
          echo "DB_USER=test" >> .env
          echo "DB_NAME=test" >> .env
          echo "DB_HOST=localhost" >> .env
